"""empty message

Revision ID: df3a905bbd69
Revises: 2dd8d30ca5ee
Create Date: 2017-07-01 20:03:31.925442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df3a905bbd69'
down_revision = '2dd8d30ca5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('for_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('restaurant', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant'], [u'restaurants.id'], name=u'menus_restaurant_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'menus_pkey')
    )
    # ### end Alembic commands ###
